package tolk.nodes;

import com.oracle.truffle.api.dsl.Cached;
import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.nodes.ExplodeLoop;
import com.oracle.truffle.api.nodes.UnexpectedResultException;
import com.oracle.truffle.api.nodes.NodeInfo;

/**
 * ### JolkMessageSendNode
 * 
 * The primary AST node for the #message dispatch.
 * 
 * By utilizing `@NodeChild` for the receiver and setting `inline = false` 
 * for the dispatcher, we ensure structural stability and prevent 
 * code-size explosion in the AST's most common node.
 */
@NodeInfo(shortName = "msg")
@NodeChild(value = "receiverNode", type = JolkNode.class)
public abstract class JolkMessageSendNode extends JolkExpressionNode {

    @Children private final JolkNode[] argumentNodes;
    private final String selector;

    /**
     * Constructor for the DSL.
     * 
     * Note: The receiverNode is managed by the DSL via `@NodeChild`.
     * The generated factory `JolkMessageSendNodeGen.create` will expect
     * the receiver node as the first argument, followed by the 
     * constructor arguments below.
     */
    public JolkMessageSendNode(String selector, JolkNode[] argumentNodes) {
        this.selector = selector;
        this.argumentNodes = argumentNodes;
    }

    /**
     * Returns the receiver node of the message send.
     * The implementation is generated by the Truffle DSL to return the @NodeChild.
     */
    public abstract JolkNode getReceiverNode();

    public JolkNode[] getArgumentNodes() {
        return argumentNodes;
    }

    public String getSelector() {
        return selector;
    }

    /**
     * Initiates the message send logic.
     * 
     * @param frame The current execution frame.
     * @param receiver The evaluated result of the receiverNode child.
     * @param dispatchNode The adopted (non-inlined) dispatcher.
     */
    @Specialization
    @ExplodeLoop
    public Object doSend(VirtualFrame frame, Object receiver,
                         @Cached JolkDispatchNode dispatchNode) {
        int arity = argumentNodes.length;

        // INDUSTRIAL OPTIMIZATION: Bypass array allocation for common message arities.
        if (arity == 0) {
            return dispatchNode.execute0(frame, receiver, selector);
        } else if (arity == 1) {
            Object arg0 = argumentNodes[0].executeGeneric(frame);
            return dispatchNode.execute1(frame, receiver, selector, arg0);
        } else if (arity == 2) {
            Object arg0 = argumentNodes[0].executeGeneric(frame);
            Object arg1 = argumentNodes[1].executeGeneric(frame);
            return dispatchNode.execute2(frame, receiver, selector, arg0, arg1);
        }

        Object[] args = new Object[arity];
        for (int i = 0; i < arity; i++) {
            args[i] = argumentNodes[i].executeGeneric(frame);
        }
        return dispatchNode.execute(frame, receiver, selector, args);
    }

    @Override
    public long executeLong(VirtualFrame frame) throws UnexpectedResultException {
        Object result = executeGeneric(frame);
        if (result instanceof Long l) {
            return l;
        }
        throw new UnexpectedResultException(result);
    }

    @Override
    public boolean executeBoolean(VirtualFrame frame) throws UnexpectedResultException {
        Object result = executeGeneric(frame);
        if (result instanceof Boolean b) {
            return b;
        }
        throw new UnexpectedResultException(result);
    }

    /**
     * The entry point for the Truffle DSL to implement the child evaluation 
     * and specialization dispatch.
     * 
     * @param frame The current execution frame.
     * @return The result of the message send.
     */
    @Override
    public abstract Object executeGeneric(VirtualFrame frame);
}